const CONTACT={name:'김경민',title:'Brand Partner',company:'LAVA LABS',phoneDisplay:'010-9057-3970',phone:'+821090573970',email:'info@lavalabs.co.kr',website:'https://lavalabs.co.kr',address:'경기도 고양시 일산서구 일현로 47, 2층 Lava Labs'};
const EMAILJS={publicKey:'p42-VpAOVAyoRBlj6',serviceId:'service_juabonc',adminTemplateId:'template_swo1fzm',confirmationTemplateId:'template_u2ljxck'};
let toastTimer,lastFocusedElement=null,qrCreated=false;
function showToast(message){const toast=document.getElementById('toast');if(!toast)return;clearTimeout(toastTimer);toast.textContent=message;toast.classList.add('is-visible');toastTimer=setTimeout(()=>toast.classList.remove('is-visible'),2400)}
async function copyText(text,successMessage='복사했습니다.'){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text)}else{const textarea=document.createElement('textarea');textarea.value=text;textarea.setAttribute('readonly','');textarea.style.position='fixed';textarea.style.opacity='0';document.body.appendChild(textarea);textarea.select();document.execCommand('copy');textarea.remove()}showToast(successMessage);return true}catch(error){console.error('Clipboard error:',error);showToast('복사하지 못했습니다.');return false}}
function downloadVCard(){const vcard=['BEGIN:VCARD','VERSION:3.0',`FN:${CONTACT.name}`,`N:${CONTACT.name};;;;`,`TITLE:${CONTACT.title}`,`ORG:${CONTACT.company}`,`TEL;TYPE=CELL:${CONTACT.phone}`,`EMAIL;TYPE=WORK:${CONTACT.email}`,`URL:${CONTACT.website}`,`ADR;TYPE=WORK:;;${CONTACT.address};;;;`,'END:VCARD'].join('\r\n');const blob=new Blob(['\ufeff',vcard],{type:'text/vcard;charset=utf-8'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${CONTACT.company}_${CONTACT.name}.vcf`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);showToast('연락처 파일을 저장했습니다.')}
async function shareCard(){const shareData={title:`${CONTACT.company} | ${CONTACT.name} ${CONTACT.title}`,text:`${CONTACT.name} · ${CONTACT.title}\n${CONTACT.phoneDisplay}\n${CONTACT.email}`,url:window.location.href.split('#')[0]};if(navigator.share){try{await navigator.share(shareData);return}catch(error){if(error.name==='AbortError')return}}await copyText(shareData.url,'명함 주소를 복사했습니다.')}
function openContactModal(){const modal=document.getElementById('contactModal');if(!modal)return;lastFocusedElement=document.activeElement;modal.classList.add('is-open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');setTimeout(()=>modal.querySelector('input:not(.honeypot)')?.focus(),50)}
function closeContactModal(){const modal=document.getElementById('contactModal');if(!modal)return;modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');lastFocusedElement?.focus()}
function validateForm(form){let valid=true;form.querySelectorAll('[required]').forEach(field=>{const fieldValid=field.checkValidity()&&field.value.trim()!=='';field.setAttribute('aria-invalid',String(!fieldValid));if(!fieldValid)valid=false});return valid}
function buildMailtoFallback(data){const subject=encodeURIComponent(`[LAVA LABS 문의] ${data.project_field} · ${data.user_name}`);const body=encodeURIComponent([`이름: ${data.user_name}`,`이메일: ${data.user_email}`,`연락처: ${data.user_phone}`,`클라이언트 구분: ${data.client_type}`,`희망 분야: ${data.project_field}`,`예산: ${data.budget}`,`일정: ${data.timeline}`,`연락 수단: ${data.contact_preference}`,'',data.message].join('\n'));window.location.href=`mailto:${CONTACT.email}?subject=${subject}&body=${body}`}
async function submitContactForm(event){event.preventDefault();const form=event.currentTarget,status=document.getElementById('formStatus'),submitButton=form.querySelector('button[type="submit"]'),submitLabel=submitButton.querySelector('span');if(form.elements.website.value)return;if(!validateForm(form)){status.textContent='필수 항목을 확인해 주세요.';form.querySelector('[aria-invalid="true"]')?.focus();return}const formData=new FormData(form);const data={user_name:formData.get('user_name').trim(),user_email:formData.get('user_email').trim(),user_phone:formData.get('user_phone').trim()||'미입력',client_type:formData.get('client_type'),project_field:formData.get('project_field'),budget:formData.get('budget')||'협의',timeline:formData.get('timeline')||'협의',meeting_location:'온라인/오프라인 협의',contact_preference:formData.get('contact_preference')||'이메일',message:formData.get('message').trim()};submitButton.disabled=true;submitLabel.textContent='전송 중...';status.textContent='';try{if(!window.emailjs){buildMailtoFallback(data);status.textContent='메일 앱을 열었습니다.';return}window.emailjs.init(EMAILJS.publicKey);await window.emailjs.send(EMAILJS.serviceId,EMAILJS.adminTemplateId,data);try{await window.emailjs.send(EMAILJS.serviceId,EMAILJS.confirmationTemplateId,{user_name:data.user_name,user_email:data.user_email,project_field:data.project_field,budget:data.budget,timeline:data.timeline})}catch(error){console.warn('Confirmation email failed:',error)}form.reset();form.querySelectorAll('[aria-invalid]').forEach(field=>field.removeAttribute('aria-invalid'));status.textContent='문의가 정상적으로 전송되었습니다.';showToast('문의가 전송되었습니다.');setTimeout(closeContactModal,900)}catch(error){console.error('EmailJS error:',error);status.textContent='전송에 실패했습니다. 이메일로 다시 시도해 주세요.';showToast('문의 전송에 실패했습니다.')}finally{submitButton.disabled=false;submitLabel.textContent='문의 보내기'}}
function createQrCode(){if(qrCreated||!window.QRCode)return;const target=document.getElementById('qrcode');if(!target)return;const url=`${window.location.origin}${window.location.pathname}`;new window.QRCode(target,{text:url,width:150,height:150,correctLevel:window.QRCode.CorrectLevel.M});qrCreated=true}
function openQr(){createQrCode();const popover=document.getElementById('qrPopover');popover?.classList.add('is-open');popover?.setAttribute('aria-hidden','false')}
function closeQr(){const popover=document.getElementById('qrPopover');popover?.classList.remove('is-open');popover?.setAttribute('aria-hidden','true')}
function initRevealAnimations(){const items=document.querySelectorAll('.reveal');if(matchMedia('(prefers-reduced-motion: reduce)').matches||!('IntersectionObserver'in window)){items.forEach(item=>item.classList.add('is-visible'));return}const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.12});items.forEach(item=>observer.observe(item))}
function trapModalFocus(event){const modal=document.getElementById('contactModal');if(!modal?.classList.contains('is-open')||event.key!=='Tab')return;const focusable=[...modal.querySelectorAll('button, [href], input:not([tabindex="-1"]), select, textarea')].filter(element=>!element.disabled&&element.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
function init(){document.getElementById('currentYear').textContent=new Date().getFullYear();initRevealAnimations();document.querySelectorAll('[data-copy]').forEach(element=>element.addEventListener('click',()=>copyText(element.dataset.copy)));document.querySelectorAll('[data-download-vcard]').forEach(element=>element.addEventListener('click',downloadVCard));document.querySelectorAll('[data-share]').forEach(element=>element.addEventListener('click',shareCard));document.querySelectorAll('[data-open-contact]').forEach(element=>element.addEventListener('click',openContactModal));document.querySelectorAll('[data-close-contact]').forEach(element=>element.addEventListener('click',closeContactModal));document.querySelectorAll('[data-open-qr]').forEach(element=>element.addEventListener('click',openQr));document.querySelectorAll('[data-close-qr]').forEach(element=>element.addEventListener('click',closeQr));document.getElementById('contactForm')?.addEventListener('submit',submitContactForm);document.querySelectorAll('#contactForm input, #contactForm select, #contactForm textarea').forEach(field=>field.addEventListener('input',()=>field.removeAttribute('aria-invalid')));document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeContactModal();closeQr()}trapModalFocus(event)});document.addEventListener('click',event=>{const popover=document.getElementById('qrPopover');if(popover?.classList.contains('is-open')&&!popover.contains(event.target)&&!event.target.closest('[data-open-qr]'))closeQr()})}
document.addEventListener('DOMContentLoaded',init);
